### ISSUE TITLE
Dang thing doesn't seem to know what a namespace is

### ISSUE THREAD

**Issue by dhnaranjo** [digital-fabric/rubyoshka#14]
The following lil script
```
require 'bundler/setup'
require 'papercraft'

module Namespaced
  Title = ->(title) { h1 title }
end


layout = Papercraft.html { |title|
  html5 {
    head { Namespaced::Title(title) }
  }
}

puts layout.render("Title content")
```

Yields this:
```
dazmin@Desmonds-MacBook-Pro ~ % ruby example.rb
example.rb:11:in `block (3 levels) in <main>': undefined method `Title' for Namespaced:Module (NoMethodError)
        from /Users/dazmin/.local/share/rubies/ruby-3.1.1/lib/ruby/gems/3.1.0/gems/papercraft-0.24/lib/papercraft/tags.rb:33:in `instance_eval'
        from /Users/dazmin/.local/share/rubies/ruby-3.1.1/lib/ruby/gems/3.1.0/gems/papercraft-0.24/lib/papercraft/tags.rb:33:in `head'
        from /Users/dazmin/.local/share/rubies/ruby-3.1.1/lib/ruby/gems/3.1.0/gems/papercraft-0.24/lib/papercraft/tags.rb:171:in `method_missing'
        from example.rb:11:in `block (2 levels) in <main>'
        from /Users/dazmin/.local/share/rubies/ruby-3.1.1/lib/ruby/gems/3.1.0/gems/papercraft-0.24/lib/papercraft/tags.rb:33:in `instance_eval'
        from /Users/dazmin/.local/share/rubies/ruby-3.1.1/lib/ruby/gems/3.1.0/gems/papercraft-0.24/lib/papercraft/tags.rb:33:in `html'
        from /Users/dazmin/.local/share/rubies/ruby-3.1.1/lib/ruby/gems/3.1.0/gems/papercraft-0.24/lib/papercraft/tags.rb:171:in `method_missing'
        from /Users/dazmin/.local/share/rubies/ruby-3.1.1/lib/ruby/gems/3.1.0/gems/papercraft-0.24/lib/papercraft/html.rb:28:in `html5'
        from example.rb:10:in `block in <main>'
        from /Users/dazmin/.local/share/rubies/ruby-3.1.1/lib/ruby/gems/3.1.0/gems/papercraft-0.24/lib/papercraft/template.rb:123:in `instance_exec'
        from /Users/dazmin/.local/share/rubies/ruby-3.1.1/lib/ruby/gems/3.1.0/gems/papercraft-0.24/lib/papercraft/template.rb:123:in `block in render'
        from /Users/dazmin/.local/share/rubies/ruby-3.1.1/lib/ruby/gems/3.1.0/gems/papercraft-0.24/lib/papercraft/renderer.rb:88:in `instance_eval'
        from /Users/dazmin/.local/share/rubies/ruby-3.1.1/lib/ruby/gems/3.1.0/gems/papercraft-0.24/lib/papercraft/renderer.rb:88:in `initialize'
        from /Users/dazmin/.local/share/rubies/ruby-3.1.1/lib/ruby/gems/3.1.0/gems/papercraft-0.24/lib/papercraft/tags.rb:52:in `initialize'
        from /Users/dazmin/.local/share/rubies/ruby-3.1.1/lib/ruby/gems/3.1.0/gems/papercraft-0.24/lib/papercraft/template.rb:121:in `new'
        from /Users/dazmin/.local/share/rubies/ruby-3.1.1/lib/ruby/gems/3.1.0/gems/papercraft-0.24/lib/papercraft/template.rb:121:in `render'
        from example.rb:15:in `<main>'
dazmin@Desmonds-MacBook-Pro ~ % 
```

Then we got this:
```
require 'bundler/setup'
require 'papercraft'

module Namespaced
  Title = ->(title) { h1 title }

  Layout = Papercraft.html { |title|
      html5 {
        head { Title(title) }
      }
    }
end

puts Namespaced::Layout.render("Title content")
```

Which gives:
```
<!DOCTYPE html><html><head><Title>Title content</Title></head></html>
```

Which I think is a different problem?

Yeah, so I think the problems are:
- You can't use a namespaced constant.
- You can't use a constant in the same namespace as you unless you're chillin in the root namespace.

I tried to trace what was going on, but when I tucked into the gem it was quickly clear that you are playing this game on another level than me.

**Comment by noteflakes** [comment]
Papercraft does not currently support namespaced constants as components.
